//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Admin_Pdv_Lauren.WS_Pool1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_Rem_File_PDVSoap", Namespace="http://tempuri.org/")]
    public partial class WS_Rem_File_PDV : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback calcOperationCompleted;
        
        private System.Threading.SendOrPostCallback writeTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemMdtOperationCompleted;
        
        private System.Threading.SendOrPostCallback CoucouOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueFaireOperationCompleted;
        
        private System.Threading.SendOrPostCallback MajEtapeScenarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback MajCodeErreurRecepteurOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportBDDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_Rem_File_PDV() {
            this.Url = global::Admin_Pdv_Lauren.Properties.Settings.Default.Admin_Pdv_Lauren_WS_Pool1_WS_Rem_File_PDV;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event calcCompletedEventHandler calcCompleted;
        
        /// <remarks/>
        public event writeTestCompletedEventHandler writeTestCompleted;
        
        /// <remarks/>
        public event RemMdtCompletedEventHandler RemMdtCompleted;
        
        /// <remarks/>
        public event CoucouCompletedEventHandler CoucouCompleted;
        
        /// <remarks/>
        public event QueFaireCompletedEventHandler QueFaireCompleted;
        
        /// <remarks/>
        public event MajEtapeScenarioCompletedEventHandler MajEtapeScenarioCompleted;
        
        /// <remarks/>
        public event MajCodeErreurRecepteurCompletedEventHandler MajCodeErreurRecepteurCompleted;
        
        /// <remarks/>
        public event ImportBDDCompletedEventHandler ImportBDDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/calc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string calc(int a, int b) {
            object[] results = this.Invoke("calc", new object[] {
                        a,
                        b});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void calcAsync(int a, int b) {
            this.calcAsync(a, b, null);
        }
        
        /// <remarks/>
        public void calcAsync(int a, int b, object userState) {
            if ((this.calcOperationCompleted == null)) {
                this.calcOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalcOperationCompleted);
            }
            this.InvokeAsync("calc", new object[] {
                        a,
                        b}, this.calcOperationCompleted, userState);
        }
        
        private void OncalcOperationCompleted(object arg) {
            if ((this.calcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calcCompleted(this, new calcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/writeTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void writeTest(string message) {
            this.Invoke("writeTest", new object[] {
                        message});
        }
        
        /// <remarks/>
        public void writeTestAsync(string message) {
            this.writeTestAsync(message, null);
        }
        
        /// <remarks/>
        public void writeTestAsync(string message, object userState) {
            if ((this.writeTestOperationCompleted == null)) {
                this.writeTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwriteTestOperationCompleted);
            }
            this.InvokeAsync("writeTest", new object[] {
                        message}, this.writeTestOperationCompleted, userState);
        }
        
        private void OnwriteTestOperationCompleted(object arg) {
            if ((this.writeTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.writeTestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemMdt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RemMdt(string nameFile, string message, string pathSortie, string FormatSortie, string Pdv, string nameListe) {
            object[] results = this.Invoke("RemMdt", new object[] {
                        nameFile,
                        message,
                        pathSortie,
                        FormatSortie,
                        Pdv,
                        nameListe});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RemMdtAsync(string nameFile, string message, string pathSortie, string FormatSortie, string Pdv, string nameListe) {
            this.RemMdtAsync(nameFile, message, pathSortie, FormatSortie, Pdv, nameListe, null);
        }
        
        /// <remarks/>
        public void RemMdtAsync(string nameFile, string message, string pathSortie, string FormatSortie, string Pdv, string nameListe, object userState) {
            if ((this.RemMdtOperationCompleted == null)) {
                this.RemMdtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemMdtOperationCompleted);
            }
            this.InvokeAsync("RemMdt", new object[] {
                        nameFile,
                        message,
                        pathSortie,
                        FormatSortie,
                        Pdv,
                        nameListe}, this.RemMdtOperationCompleted, userState);
        }
        
        private void OnRemMdtOperationCompleted(object arg) {
            if ((this.RemMdtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemMdtCompleted(this, new RemMdtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Coucou", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Coucou(string codehex, string version) {
            object[] results = this.Invoke("Coucou", new object[] {
                        codehex,
                        version});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CoucouAsync(string codehex, string version) {
            this.CoucouAsync(codehex, version, null);
        }
        
        /// <remarks/>
        public void CoucouAsync(string codehex, string version, object userState) {
            if ((this.CoucouOperationCompleted == null)) {
                this.CoucouOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCoucouOperationCompleted);
            }
            this.InvokeAsync("Coucou", new object[] {
                        codehex,
                        version}, this.CoucouOperationCompleted, userState);
        }
        
        private void OnCoucouOperationCompleted(object arg) {
            if ((this.CoucouCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CoucouCompleted(this, new CoucouCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueFaire", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueFaire(string codehex) {
            object[] results = this.Invoke("QueFaire", new object[] {
                        codehex});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueFaireAsync(string codehex) {
            this.QueFaireAsync(codehex, null);
        }
        
        /// <remarks/>
        public void QueFaireAsync(string codehex, object userState) {
            if ((this.QueFaireOperationCompleted == null)) {
                this.QueFaireOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueFaireOperationCompleted);
            }
            this.InvokeAsync("QueFaire", new object[] {
                        codehex}, this.QueFaireOperationCompleted, userState);
        }
        
        private void OnQueFaireOperationCompleted(object arg) {
            if ((this.QueFaireCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueFaireCompleted(this, new QueFaireCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MajEtapeScenario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MajEtapeScenario(string codehex, string idScenario, string etape) {
            object[] results = this.Invoke("MajEtapeScenario", new object[] {
                        codehex,
                        idScenario,
                        etape});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MajEtapeScenarioAsync(string codehex, string idScenario, string etape) {
            this.MajEtapeScenarioAsync(codehex, idScenario, etape, null);
        }
        
        /// <remarks/>
        public void MajEtapeScenarioAsync(string codehex, string idScenario, string etape, object userState) {
            if ((this.MajEtapeScenarioOperationCompleted == null)) {
                this.MajEtapeScenarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMajEtapeScenarioOperationCompleted);
            }
            this.InvokeAsync("MajEtapeScenario", new object[] {
                        codehex,
                        idScenario,
                        etape}, this.MajEtapeScenarioOperationCompleted, userState);
        }
        
        private void OnMajEtapeScenarioOperationCompleted(object arg) {
            if ((this.MajEtapeScenarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MajEtapeScenarioCompleted(this, new MajEtapeScenarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MajCodeErreurRecepteur", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MajCodeErreurRecepteur(string codehex, string idScenario, string CodeErreur) {
            object[] results = this.Invoke("MajCodeErreurRecepteur", new object[] {
                        codehex,
                        idScenario,
                        CodeErreur});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MajCodeErreurRecepteurAsync(string codehex, string idScenario, string CodeErreur) {
            this.MajCodeErreurRecepteurAsync(codehex, idScenario, CodeErreur, null);
        }
        
        /// <remarks/>
        public void MajCodeErreurRecepteurAsync(string codehex, string idScenario, string CodeErreur, object userState) {
            if ((this.MajCodeErreurRecepteurOperationCompleted == null)) {
                this.MajCodeErreurRecepteurOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMajCodeErreurRecepteurOperationCompleted);
            }
            this.InvokeAsync("MajCodeErreurRecepteur", new object[] {
                        codehex,
                        idScenario,
                        CodeErreur}, this.MajCodeErreurRecepteurOperationCompleted, userState);
        }
        
        private void OnMajCodeErreurRecepteurOperationCompleted(object arg) {
            if ((this.MajCodeErreurRecepteurCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MajCodeErreurRecepteurCompleted(this, new MajCodeErreurRecepteurCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportBDD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ImportBDD(string codehex, string idScenario, string bloc) {
            object[] results = this.Invoke("ImportBDD", new object[] {
                        codehex,
                        idScenario,
                        bloc});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ImportBDDAsync(string codehex, string idScenario, string bloc) {
            this.ImportBDDAsync(codehex, idScenario, bloc, null);
        }
        
        /// <remarks/>
        public void ImportBDDAsync(string codehex, string idScenario, string bloc, object userState) {
            if ((this.ImportBDDOperationCompleted == null)) {
                this.ImportBDDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportBDDOperationCompleted);
            }
            this.InvokeAsync("ImportBDD", new object[] {
                        codehex,
                        idScenario,
                        bloc}, this.ImportBDDOperationCompleted, userState);
        }
        
        private void OnImportBDDOperationCompleted(object arg) {
            if ((this.ImportBDDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportBDDCompleted(this, new ImportBDDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void calcCompletedEventHandler(object sender, calcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void writeTestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RemMdtCompletedEventHandler(object sender, RemMdtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemMdtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemMdtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CoucouCompletedEventHandler(object sender, CoucouCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CoucouCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CoucouCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QueFaireCompletedEventHandler(object sender, QueFaireCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueFaireCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueFaireCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MajEtapeScenarioCompletedEventHandler(object sender, MajEtapeScenarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MajEtapeScenarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MajEtapeScenarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MajCodeErreurRecepteurCompletedEventHandler(object sender, MajCodeErreurRecepteurCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MajCodeErreurRecepteurCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MajCodeErreurRecepteurCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ImportBDDCompletedEventHandler(object sender, ImportBDDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportBDDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportBDDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591